// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dario.Robles.Store.Service.Domain.Orders.Entities;

public partial class Item
{
    public Guid ItemId { get; set; }

    public Guid OrderId { get; set; }

    public string Name { get; set; }

    public int Quantity { get; set; }

    public virtual Order Order { get; set; }
}